' Developer Express Code Central Example:
' How to create Checkable Grouping in GridControl
' 
' The example demonstrates how to add the CheckBox functionality to each GroupRow
' in TableView. The basic idea is to allow a user to easily check or uncheck the
' necessary group of items in GridControl.
' 
' The functionality is realized as
' behavior in the CheckableGroupBehavior class, which can be attached to
' GridControl. It automatically sets GroupValueTemplate using the GroupCheckBox
' class, which is inherited from the CheckBox class. The CheckableGroupBehavior's
' CheckableProperty must be set and has to contain the name of the property in a
' row data object, which will be used to check items. The property has to be of
' the Boolean type.
' 
' You can easily add the same functionality to your project by
' using the CheckableGroupBehavior class and attaching it as behavior to your
' GridControl.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=T127563
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace DevExpress.Example03.Properties

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(DevExpress.Example03.Properties.Resources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(DevExpress.Example03.Properties.Resources).Assembly)
                    DevExpress.Example03.Properties.Resources.resourceMan = temp
                End If

                Return DevExpress.Example03.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return DevExpress.Example03.Properties.Resources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                DevExpress.Example03.Properties.Resources.resourceCulture = value
            End Set
        End Property
    End Class
End Namespace
